services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    ports:
      - 80:8080
      - 8001:8001
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command:
      - -c
      - /etc/envoy/envoy.yaml
      - --log-level
      - info

  opa:
    image: openpolicyagent/opa:latest-envoy
    ports:
      - 8181:8181
      - 9191:9191
      - 8282:8282
    command:
      - run
      - --server
      - --addr=0.0.0.0:8181
      - --diagnostic-addr=0.0.0.0:8282
      - --set=plugins.envoy_ext_authz_grpc.addr=0.0.0.0:9191
      - --set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow
      - --set=decision_logs.console=true
      - --set=distributed_tracing.type=grpc
      - --set=distributed_tracing.address=jaeger:4317
      - --log-level=info
      - --log-format=json
      - --watch
      - /policy
    volumes:
      - ./policy:/policy

  service-envoy-1:
    image: traefik/whoami
    command:
       - --name=service-envoy-1
  service-envoy-2:
    image: traefik/whoami
    command:
       - --name=service-envoy-2
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
